Accessibility add-on in React Vanilla Components
adobe/aem-forms-headless-components pull request #140
Opened 2024-05-21 08:18 UTC by pavi41

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-05-22 06:35 UTC, rismehta commented on packages/react-vanilla-components/src/utils/utils.tsx
> +  export const syncAriaDescribedBy = (id: string, tooltip: string | undefined, description: string | undefined, error: string | undefined) => {
```
export const syncAriaDescribedBy = (id: string, tooltip?: string, description?: string, error?: string) => {
    const descriptions = [];

    if (description) {
        descriptions.push(`${id}__longdescription`);
    }
    if (tooltip) {
        descriptions.push(`${id}__shortdescription`);
    }
    if (error) {
        descriptions.push(`${id}__errormessage`);
    }

    return descriptions.join(' ');
};
```

2024-05-22 06:36 UTC, rismehta requested changes
check comments

2024-05-23 10:53 UTC, pavi41 commented on packages/react-vanilla-components/src/utils/utils.tsx
> +  export const syncAriaDescribedBy = (id: string, tooltip: string | undefined, description: string | undefined, error: string | undefined) => {
implemented!

2024-05-27 08:50 UTC, rismehta approved these changes

2024-05-27 08:50 UTC, merged