[FORMS-9143] implement radio button component
adobe/aem-forms-headless-components pull request #76
Opened 2023-06-22 09:05 UTC by Aabha1

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-28 04:38 UTC, amit-mnnit commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +  const k = 'afs:layout';
k?

2023-06-28 04:39 UTC, amit-mnnit commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +  }
const options = enumNames?.length ? enumNames : enums;

2023-06-28 04:39 UTC, amit-mnnit commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +        <FormLabel error={isError}>
add this condition on FormLabel

2023-06-28 04:40 UTC, amit-mnnit commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +          {options.map((option) => {
please check https://github.com/adobe/aem-forms-headless-components/blob/main/packages/react-native/src/components/CheckboxGroup.tsx#L31

2023-06-28 04:40 UTC, amit-mnnit commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +          defaultValue=''
?

2023-06-28 04:40 UTC, amit-mnnit requested changes
Please incorporate all the comments and also test localization

2023-07-03 09:40 UTC, Aabha1 commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +  const k = 'afs:layout';
Removed k

2023-07-03 09:41 UTC, Aabha1 commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +  }
Rendered as convection

2023-07-03 09:41 UTC, Aabha1 commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +        <FormLabel error={isError}>
Added condition

2023-07-03 09:41 UTC, Aabha1 commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +          {options.map((option) => {
Implemented as convection

2023-07-03 09:42 UTC, Aabha1 commented on packages/material-ui-based-components/src/components/Radiobutton.tsx
> +          defaultValue=''
Removed unnecessary attributes.

2023-08-28 05:56 UTC, merged